/*
 * Copyright 2014 Igor Maznitsa (http://www.igormaznitsa.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.igormaznitsa.jprol.easygui;

import static java.util.Objects.requireNonNull;

import com.igormaznitsa.jprol.kbase.inmemory.InMemoryKnowledgeBase;
import com.igormaznitsa.jprol.logic.JProlContext;
import java.io.CharArrayWriter;
import java.io.PrintWriter;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The class implements the dialog window which allows user to take a look at
 * the snapshot of the current knowledge base state because it is a very
 * specialized auxiliary class, it is not described very precisely
 *
 * @author Igor Maznitsa (igor.maznitsa@igormaznitsa.com)
 */
public class KnowledgeBaseSnapshotViewDialog extends JDialog {

  private static final long serialVersionUID = -4927120918645871928L;
  private JButton buttonClose;
  private PrologSourceEditor textViewer;

  /**
   * Creates new form KnowledgeBaseSnapshotViewDialog
   */
  public KnowledgeBaseSnapshotViewDialog(final JFrame parent, final JProlContext context) {
    super(parent, true);
    initComponents();
    textViewer.getEditor().setEditable(false);
    textViewer.setTitle("Knowledge base");

    if (context != null) {
      final InMemoryKnowledgeBase inMemoryBase = (InMemoryKnowledgeBase) context.getKnowledgeBase();
      final CharArrayWriter charArray = new CharArrayWriter(8096);
      try (PrintWriter writer = new PrintWriter(charArray, true)) {
        inMemoryBase.printStateAsSrc(writer);
      }
      textViewer.getEditor().setText(charArray.toString());
    }

    this.getRootPane().setDefaultButton(this.buttonClose);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    textViewer = new PrologSourceEditor();
    buttonClose = new JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Current or last knowledge base snapshot");
    getContentPane().setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1000.0;
    gridBagConstraints.weighty = 1000.0;
    getContentPane().add(textViewer, gridBagConstraints);

    buttonClose.setIcon(new javax.swing.ImageIcon(requireNonNull(
        getClass().getResource("/com/igormaznitsa/jprol/easygui/icons/cross.png")))); // NOI18N
    buttonClose.setText("Close");
    buttonClose.addActionListener(this::ButtonCloseActionPerformed);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 8;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(buttonClose, gridBagConstraints);

    pack();
  }

  private void ButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {
    dispose();
  }
}
