#!/bin/sh
JAVA_FLAGS="-client -XX:+IgnoreUnrecognizedVMOptions -Xss50M -Xmx2G --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
JAVA_RUN=$APPDIR/jre/bin/java
$JAVA_RUN $JAVA_FLAGS $JAVA_EXTRA_GFX_FLAGS -jar $APPDIR/jprol-gui*.jar $@

